/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;

import Clases.Developer;
import Clases.Estudio;

/**
 *
 * @author Natalia
 */
public class Ventana extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public Ventana() {
        initComponents();        
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        Config = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        saveButton = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        Cont_Deadline = new javax.swing.JSpinner();
        jButton1 = new javax.swing.JButton();
        Cartoon = new javax.swing.JPanel();
        Cont_Guionista_PW_CN = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Cont_Guionista_CN = new javax.swing.JSpinner();
        jLabel3 = new javax.swing.JLabel();
        Cont_Diseñador_CN = new javax.swing.JSpinner();
        jLabel4 = new javax.swing.JLabel();
        Cont_Animador_CN = new javax.swing.JSpinner();
        jLabel5 = new javax.swing.JLabel();
        Cont_Actor_Doblaje_CN = new javax.swing.JSpinner();
        jLabel11 = new javax.swing.JLabel();
        Cont_Ensamblador_CN = new javax.swing.JSpinner();
        Nick = new javax.swing.JPanel();
        Cont_Guionista_PW_NK = new javax.swing.JSpinner();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Cont_Guionista_NK = new javax.swing.JSpinner();
        jLabel8 = new javax.swing.JLabel();
        Cont_Diseñador_NK = new javax.swing.JSpinner();
        jLabel9 = new javax.swing.JLabel();
        Cont_Animador_NK = new javax.swing.JSpinner();
        jLabel10 = new javax.swing.JLabel();
        Cont_Actor_Doblaje_NK = new javax.swing.JSpinner();
        jLabel12 = new javax.swing.JLabel();
        Cont_Ensamblador_NK = new javax.swing.JSpinner();
        Graf = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Config.setBackground(new java.awt.Color(204, 153, 255));
        Config.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("DIAS ENTRE DEADLINES: ");
        Config.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        saveButton.setText("GUARDAR");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });
        Config.add(saveButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, -1, -1));

        jLabel14.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("GUARDAR: ");
        Config.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        Cont_Deadline.setEditor(new javax.swing.JSpinner.NumberEditor(Cont_Deadline, ""));
        Cont_Deadline.setValue(1);
        Cont_Deadline.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                Cont_DeadlineStateChanged(evt);
            }
        });
        Config.add(Cont_Deadline, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 150, 80, 20));

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        Config.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 70, -1, -1));

        jTabbedPane1.addTab("Config", Config);

        Cartoon.setBackground(new java.awt.Color(0, 0, 0));
        Cartoon.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Cont_Guionista_PW_CN.setEditor(new javax.swing.JSpinner.NumberEditor(Cont_Diseñador_CN, ""));
        Cont_Guionista_PW_CN.setValue(1);
        Cont_Guionista_PW_CN.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                Cont_Guionista_PW_CNStateChanged(evt);
            }
        });
        Cartoon.add(Cont_Guionista_PW_CN, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 290, 80, 20));

        jLabel1.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        jLabel1.setText("ENSAMBLADORES:");
        Cartoon.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 210, -1));

        jLabel2.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        jLabel2.setText("GUIONISTAS:");
        Cartoon.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        Cont_Guionista_CN.setEditor(new javax.swing.JSpinner.NumberEditor(Cont_Guionista_CN, ""));
        Cont_Guionista_CN.setValue(1);
        Cont_Guionista_CN.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                Cont_Guionista_CNStateChanged(evt);
            }
        });
        Cartoon.add(Cont_Guionista_CN, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 130, 80, 20));

        jLabel3.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        jLabel3.setText("DISEÑADORES DE  PERSONAJES:");
        Cartoon.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 220, -1));

        Cont_Diseñador_CN.setEditor(new javax.swing.JSpinner.NumberEditor(Cont_Diseñador_CN, ""));
        Cont_Diseñador_CN.setValue(1);
        Cont_Diseñador_CN.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                Cont_Diseñador_CNStateChanged(evt);
            }
        });
        Cartoon.add(Cont_Diseñador_CN, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 170, 80, 20));

        jLabel4.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        jLabel4.setText("ANIMADORES DE  PERSONAJES:");
        Cartoon.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 220, -1));

        Cont_Animador_CN.setEditor(new javax.swing.JSpinner.NumberEditor(Cont_Diseñador_CN, ""));
        Cont_Animador_CN.setValue(1);
        Cont_Animador_CN.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                Cont_Animador_CNStateChanged(evt);
            }
        });
        Cartoon.add(Cont_Animador_CN, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 210, 80, 20));

        jLabel5.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        jLabel5.setText("ACTORES DE DOBLAJE:");
        Cartoon.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 210, -1));

        Cont_Actor_Doblaje_CN.setEditor(new javax.swing.JSpinner.NumberEditor(Cont_Diseñador_CN, ""));
        Cont_Actor_Doblaje_CN.setValue(1);
        Cont_Actor_Doblaje_CN.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                Cont_Actor_Doblaje_CNStateChanged(evt);
            }
        });
        Cartoon.add(Cont_Actor_Doblaje_CN, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 250, 80, 20));

        jLabel11.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        jLabel11.setText("GUIONISTAS DE PLOT-TWIST:");
        Cartoon.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 210, -1));

        Cont_Ensamblador_CN.setEditor(new javax.swing.JSpinner.NumberEditor(Cont_Diseñador_CN, ""));
        Cont_Ensamblador_CN.setValue(1);
        Cont_Ensamblador_CN.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                Cont_Ensamblador_CNStateChanged(evt);
            }
        });
        Cartoon.add(Cont_Ensamblador_CN, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 330, 80, -1));

        jTabbedPane1.addTab("Cartoon", Cartoon);

        Nick.setBackground(new java.awt.Color(255, 153, 0));
        Nick.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Cont_Guionista_PW_NK.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Cont_Guionista_PW_NK.setEditor(new javax.swing.JSpinner.NumberEditor(Cont_Guionista_NK, ""));
        Cont_Guionista_PW_NK.setValue(1);
        Cont_Guionista_PW_NK.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                Cont_Guionista_PW_NKStateChanged(evt);
            }
        });
        Nick.add(Cont_Guionista_PW_NK, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 290, 80, 20));

        jLabel6.setBackground(new java.awt.Color(0, 0, 0));
        jLabel6.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("GUIONISTAS DE PLOT-TWIST:");
        Nick.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 210, -1));

        jLabel7.setBackground(new java.awt.Color(0, 0, 0));
        jLabel7.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("GUIONISTAS:");
        Nick.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        Cont_Guionista_NK.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Cont_Guionista_NK.setEditor(new javax.swing.JSpinner.NumberEditor(Cont_Guionista_NK, ""));
        Cont_Guionista_NK.setValue(1);
        Cont_Guionista_NK.setVerifyInputWhenFocusTarget(false);
        Cont_Guionista_NK.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                Cont_Guionista_NKStateChanged(evt);
            }
        });
        Nick.add(Cont_Guionista_NK, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 130, 80, 20));

        jLabel8.setBackground(new java.awt.Color(0, 0, 0));
        jLabel8.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("DISEÑADORES DE  PERSONAJES:");
        Nick.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 220, -1));

        Cont_Diseñador_NK.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Cont_Diseñador_NK.setEditor(new javax.swing.JSpinner.NumberEditor(Cont_Guionista_NK, ""));
        Cont_Diseñador_NK.setValue(1);
        Cont_Diseñador_NK.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                Cont_Diseñador_NKStateChanged(evt);
            }
        });
        Nick.add(Cont_Diseñador_NK, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 170, 80, 20));

        jLabel9.setBackground(new java.awt.Color(0, 0, 0));
        jLabel9.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("ANIMADORES DE  PERSONAJES:");
        Nick.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 220, -1));

        Cont_Animador_NK.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Cont_Animador_NK.setEditor(new javax.swing.JSpinner.NumberEditor(Cont_Guionista_NK, ""));
        Cont_Animador_NK.setValue(1);
        Cont_Animador_NK.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                Cont_Animador_NKStateChanged(evt);
            }
        });
        Nick.add(Cont_Animador_NK, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 210, 80, 20));

        jLabel10.setBackground(new java.awt.Color(0, 0, 0));
        jLabel10.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("ACTORES DE DOBLAJE:");
        Nick.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 210, -1));

        Cont_Actor_Doblaje_NK.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Cont_Actor_Doblaje_NK.setEditor(new javax.swing.JSpinner.NumberEditor(Cont_Guionista_NK, ""));
        Cont_Actor_Doblaje_NK.setValue(1);
        Cont_Actor_Doblaje_NK.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                Cont_Actor_Doblaje_NKStateChanged(evt);
            }
        });
        Nick.add(Cont_Actor_Doblaje_NK, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 250, 80, 20));

        jLabel12.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("ENSAMBLADORES:");
        Nick.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 210, -1));

        Cont_Ensamblador_NK.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Cont_Ensamblador_NK.setEditor(new javax.swing.JSpinner.NumberEditor(Cont_Guionista_NK, ""));
        Cont_Ensamblador_NK.setValue(1);
        Cont_Ensamblador_NK.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                Cont_Ensamblador_NKStateChanged(evt);
            }
        });
        Nick.add(Cont_Ensamblador_NK, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 330, 80, -1));

        jTabbedPane1.addTab("Nick", Nick);

        Graf.setBackground(new java.awt.Color(204, 153, 255));
        Graf.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jTabbedPane1.addTab("Grafico", Graf);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 820, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Cont_Guionista_CNStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_Cont_Guionista_CNStateChanged
        if((int)this.Cont_Guionista_CN.getValue() <= 0){
            this.Cont_Guionista_CN.setValue(1);
            this.repaint();
        }
    }//GEN-LAST:event_Cont_Guionista_CNStateChanged

    private void Cont_Diseñador_CNStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_Cont_Diseñador_CNStateChanged
        if((int)this.Cont_Diseñador_CN.getValue() <= 0){
            this.Cont_Diseñador_CN.setValue(1);
            this.repaint();
        }
    }//GEN-LAST:event_Cont_Diseñador_CNStateChanged

    private void Cont_Animador_CNStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_Cont_Animador_CNStateChanged
        if((int)this.Cont_Animador_CN.getValue() <= 0){
            this.Cont_Animador_CN.setValue(1);
            this.repaint();
        }
    }//GEN-LAST:event_Cont_Animador_CNStateChanged

    private void Cont_Actor_Doblaje_CNStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_Cont_Actor_Doblaje_CNStateChanged
        if((int)this.Cont_Actor_Doblaje_CN.getValue() <= 0){
            this.Cont_Actor_Doblaje_CN.setValue(1);
            this.repaint();
        }
    }//GEN-LAST:event_Cont_Actor_Doblaje_CNStateChanged

    private void Cont_Guionista_PW_CNStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_Cont_Guionista_PW_CNStateChanged
        if((int)this.Cont_Guionista_PW_CN.getValue() <= 0){
            this.Cont_Guionista_PW_CN.setValue(1);
            this.repaint();
        }
    }//GEN-LAST:event_Cont_Guionista_PW_CNStateChanged

    private void Cont_Guionista_PW_NKStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_Cont_Guionista_PW_NKStateChanged
        if((int)this.Cont_Guionista_PW_NK.getValue() <= 0){
            this.Cont_Guionista_PW_NK.setValue(1);
            this.repaint();
        }
    }//GEN-LAST:event_Cont_Guionista_PW_NKStateChanged

    private void Cont_Guionista_NKStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_Cont_Guionista_NKStateChanged
        if((int)this.Cont_Guionista_NK.getValue() <= 0){
            this.Cont_Guionista_NK.setValue(1);
            this.repaint();
        }
    }//GEN-LAST:event_Cont_Guionista_NKStateChanged

    private void Cont_Diseñador_NKStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_Cont_Diseñador_NKStateChanged
        if((int)this.Cont_Diseñador_NK.getValue() <= 0){
            this.Cont_Diseñador_NK.setValue(1);
            this.repaint();
        }
    }//GEN-LAST:event_Cont_Diseñador_NKStateChanged

    private void Cont_Animador_NKStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_Cont_Animador_NKStateChanged
        if((int)this.Cont_Animador_NK.getValue() <= 0){
            this.Cont_Animador_NK.setValue(1);
            this.repaint();
        }
    }//GEN-LAST:event_Cont_Animador_NKStateChanged

    private void Cont_Actor_Doblaje_NKStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_Cont_Actor_Doblaje_NKStateChanged
        if((int)this.Cont_Actor_Doblaje_NK.getValue() <= 0){
            this.Cont_Actor_Doblaje_NK.setValue(1);
            this.repaint();
        }
    }//GEN-LAST:event_Cont_Actor_Doblaje_NKStateChanged

    private void Cont_Ensamblador_CNStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_Cont_Ensamblador_CNStateChanged
        if((int)this.Cont_Ensamblador_CN.getValue() <= 0){
            this.Cont_Ensamblador_CN.setValue(1);
            this.repaint();
        }
    }//GEN-LAST:event_Cont_Ensamblador_CNStateChanged

    private void Cont_Ensamblador_NKStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_Cont_Ensamblador_NKStateChanged
        if((int)this.Cont_Ensamblador_NK.getValue() <= 0){
            this.Cont_Ensamblador_NK.setValue(1);
            this.repaint();
        }
    }//GEN-LAST:event_Cont_Ensamblador_NKStateChanged

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_saveButtonActionPerformed

    private void Cont_DeadlineStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_Cont_DeadlineStateChanged
        if((int)this.Cont_Deadline.getValue() <= 0){
            this.Cont_Deadline.setValue(1);
            this.repaint();
        }
    }//GEN-LAST:event_Cont_DeadlineStateChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Estudio nick=new Estudio("nick",5,6);
        nick.AddDeveloper(0, 2);
//        nick.AddDeveloper(1, 1);
//        nick.AddDeveloper(2, 1);
//        nick.AddDeveloper(3, 1);
//        nick.AddDeveloper(4, 1);
//        nick.AddDeveloper(5, 1);
        //Developer guion1=new Developer(nick.getPersonalDrive(),0,20,nick.getMutex(),3000,0.5,nick.getName());
        
        //nick.getListaGuion().insertBegin(guion1);
        //guion1.start();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Cartoon;
    private javax.swing.JPanel Config;
    private javax.swing.JSpinner Cont_Actor_Doblaje_CN;
    private javax.swing.JSpinner Cont_Actor_Doblaje_NK;
    private javax.swing.JSpinner Cont_Animador_CN;
    private javax.swing.JSpinner Cont_Animador_NK;
    private javax.swing.JSpinner Cont_Deadline;
    private javax.swing.JSpinner Cont_Diseñador_CN;
    private javax.swing.JSpinner Cont_Diseñador_NK;
    private javax.swing.JSpinner Cont_Ensamblador_CN;
    private javax.swing.JSpinner Cont_Ensamblador_NK;
    private javax.swing.JSpinner Cont_Guionista_CN;
    private javax.swing.JSpinner Cont_Guionista_NK;
    private javax.swing.JSpinner Cont_Guionista_PW_CN;
    private javax.swing.JSpinner Cont_Guionista_PW_NK;
    private javax.swing.JPanel Graf;
    private javax.swing.JPanel Nick;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton saveButton;
    // End of variables declaration//GEN-END:variables
}
